import json
import os

from fastapi import FastAPI, HTTPException
from starlette.requests import Request
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import re
import hashlib
from collections import OrderedDict
from openai import AsyncOpenAI
from solidity_audit_lib.messaging import AuditBase
import asyncio

app = FastAPI()

GPT_MODEL = "anthropic/claude-3.7-sonnet"

class ROLES:
    SYSTEM = "system"
    ASSISTANT = "assistant"
    USER = "user"

# class Response(AuditBase):
#     content: str = Field(..., title="Contract code", description="Code of vulnerable contract")


client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="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",
)

# Load Mistral 7B Instruct model and tokenizer
model_name = "mistralai/Mistral-7B-Instruct-v0.2"
#model_name = "./mixtral-finetuned"
tokenizer = AutoTokenizer.from_pretrained(model_name)
# tokenizer.pad_token = tokenizer.eos_token

llm = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map="auto")

ROLE_SYSTEM = "system"
ROLE_ASSISTANT = "assistant"
ROLE_USER = "user"
def show_section(text):
    print("-"*100)
    print(text)
    print("-"*100)

def extract_json_string(text):
    """Extract the first valid JSON array from text using regex."""
    match = re.search(r"\[\s*{.*?}\s*]", text, re.DOTALL) 
    if match:
        return match.group(0)
    else:
        return "[]"

def get_gpt_prompt():
    return """
    You are helping audit a Solidity smart contract.
    Your job is to review the given Solidity code and identify only the vulnerabilities that are clearly present based on the code itself.

    Follow these strict guidelines:

    - Use the line numbers in the code to pinpoint the exact location of each vulnerability.

    - Only include issues that match one of these vulnerability classes:
    "Reentrancy", "Gas griefing", "Bad randomness", "Forced reception", "Unguarded function", "Signature replay"

    - Do not report any other types of issues.

    - Do not guess or infer intent. Only report issues that are directly observable from the code as written.

    - There must be at least one vulnerable issue. Don't return []

    - If the code is completely invalid or cannot be reviewed meaningfully, return a single issue that covers the full file.

    - Output should be in pure JSON format, with no extra text or explanation.

    Use this JSON structure:

    [
    {
        "fromLine": 10,
        "toLine": 15,
        "vulnerabilityClass": "Reentrancy",
        "description": "The withdraw function calls an external address before updating internal balance, allowing reentrancy."
    },
    {
        "fromLine": 22,
        "toLine": 22,
        "vulnerabilityClass": "Unguarded function",
        "description": "The setOwner function is externally accessible without any access control."
    }
    ]
    """

def get_gpt_prompt2(record):
    PROMPT =  f"""
You are analyzing a Solidity smart contract for vulnerabilities.

Your task is to return a JSON array. Each object in the array must describe a single security issue found in the code.

Please follow these strict guidelines:

- Use line numbers to identify where the vulnerability starts and ends.
- Use the following fields in each object:
  - fromLine: starting line of the vulnerable code
  - toLine: ending line of the vulnerable code
  - vulnerabilityClass: the type of vulnerability — use this exact string: {record["type"]},
  - description: a short explanation of how this vulnerability could be exploited
- You must include this example code for reference: {record["code"]},
- Do not include any text before or after the JSON.
- Do not include any explanations, only the JSON array.

Format your response exactly like this:

[
  {{
    "fromLine": 10,
    "toLine": 15,
    "vulnerabilityClass": "{record["type"]}",
    "description": "The withdraw function calls an external address before updating internal balance, allowing reentrancy."
  }}
]
    """
    return PROMPT

def get_prompt(solidity_code):

    numbered_code = "\n".join(
    f"{i+1}: {line}" for i, line in enumerate(solidity_code.splitlines())
    )

    PROMPT = f"""
    You are analyzing a Solidity smart contract to find vulnerabilities.
    Now analyze the following Solidity code and identify if it contains a vulnerability.
    return a JSON array where each object describes a single security issue.
    Solidity code is generated by anthropic/claude-3.7-sonnet model and it's prompt is "Generate new vulnerable contract with one of <type of vulnerabilities>"

    Use this format:
    [
    {{
        "fromLine": INT,
        "toLine": INT,
        "vulnerabilityClass": STRING,
        "description": STRING
    }}
    ]


    Rules:
    - fromLine is the line number where the vulnerable code starts.
    - toLine is the line number where the vulnerable code ends.
    - Do not include extra text or explanations.
    - Use only these vulnerabilityClass values: "Reentrancy", "Gas griefing", "Bad randomness", "Forced reception", "Unguarded function", "Signature replay".
    - Describe how the vulnerability can be exploited.
    - "// SPDX-License-Identifier: MIT" is valid solidity code
    - Return Must include fromLine, toLine, vulnerabilityClass, description
    
    Return only the JSON output.
    Code:
    {numbered_code}
    """
    return PROMPT

def get_prompt2(solidity_code, record):

    numbered_code = "\n".join(
    f"{i+1}: {line}" for i, line in enumerate(solidity_code.splitlines())
    )

    PROMPT = f"""
    You are analyzing a Solidity smart contract to find vulnerabilities.

    Given code return a JSON array where each object describes a single security issue.

    Use this format:
    [
    {{
        "fromLine": INT,
        "toLine": INT,
        "vulnerabilityClass": STRING,
        "description": STRING
    }}
    ]

    Rules:
    - fromLine is the line number where the vulnerable code starts.
    - toLine is the line number where the vulnerable code ends.
    - vulnerabilityClass is "{record["type"]}"
    - example of "{record["type"]}" type of vulnerability is "{record["code"]}"
    - Do not include extra text or explanations.
    - Explain how the vulnerability can be exploited.
    - "// SPDX-License-Identifier: MIT" is valid solidity code
    - Return Must include fromLine, toLine, vulnerabilityClass, description

    Return only the JSON output.

    Code:
    {numbered_code}
    """
    return PROMPT

def get_prompt3(solidity_code):

    numbered_code = "\n".join(
    f"{i+1}: {line}" for i, line in enumerate(solidity_code.splitlines())
    )

    PROMPT = f"""
    Return this:
    
    [
    {{
        "fromLine": 1,
        "toLine": TOTAL_LINE_COUNT,
        "vulnerabilityClass": "Invalid Code",
        "description": "The entire code is considered invalid for audit processing."
    }}
    ]
    
    Rules:
    - toLine is the line number of rows of full code
    - Do not include extra text or explanations.
    - JSON Array size is one
    
    Return only the JSON output.

    Code:
    {numbered_code}
    """
    return PROMPT

def get_prompt4(solidity_code):

    numbered_code = "\n".join(
        f"{i+1}: {line}" for i, line in enumerate(solidity_code.splitlines())
    )

    PROMPT = f"""
    You are analyzing a Solidity smart contract to find vulnerabilities.

    Analyze the following Solidity code and return ONLY one word: `True` or `False`.

    Rules:
    - Return `False` if there is ANY vulnerability or poor security practice.
    - Return `True` ONLY if the contract is completely secure.

    DO NOT explain your answer. DO NOT add any comments.
    Do NOT output contract's issues and Reason.
    Do NOT return more than ONE word.

    Solidity Code:
    {numbered_code}
    """
    return PROMPT

def find_record(contract_code_str, jsonl_file_path):
    """
    Given a contract code string and a .jsonl file path,
    return all JSON records whose 'code' is found in the contract code.
    """
    
    contract_code_clean = normalize_code(contract_code_str)
    
    matches = []
    
    # Load JSONL records
    with open(jsonl_file_path, 'r') as f:
        for line in f:
            try:
                record = json.loads(line)
            except Exception as e:
                print(f"Error {e}")
                continue
            json_code_clean = normalize_code(record['code'])

            if json_code_clean in contract_code_clean:
                matches.append(record)
    
    return matches

def normalize_code(code):
    # Remove all whitespace including newlines, tabs, spaces
    return re.sub(r'\s+', '', code)

def reference(prompt, temperature = 0.0):
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        if temperature == 0.0:
            output = llm.generate(
                **inputs, 
                max_new_tokens=8192,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id
            )
        else:
            output = llm.generate(
                **inputs, 
                max_new_tokens=8192,
                temperature=temperature,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
            
    # Calculate the length of the input prompt
    prompt_length = inputs["input_ids"].shape[1]

    # Extract only the generated tokens
    generated_tokens = output[0][prompt_length:]

    message = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    
    return message


async def gpt_reference(prompt, code, temperature=0.3):

    numbered_code = "\n".join(
    f"{i+1}: {line}" for i, line in enumerate(code.splitlines())
    )


    completion = await client.beta.chat.completions.parse(
        model=GPT_MODEL,
        messages=[
            {"role": ROLES.SYSTEM, "content": prompt},
            # Output format guidance is provided automatically by OpenAI SDK.
            {
                "role": ROLES.USER,
                "content": f"{numbered_code}",
            },
        ],
        # response_format=ValidatorTask,
        temperature=temperature,
    )
    message = completion.choices[0].message
    print(f"GPT message: {message.content}")
    if message.content:
        return message.content
    else:
        return "[]"

def find_function_position(contract_code: str, func_code: str):
    contract_lines = contract_code.splitlines()
    func_lines = func_code.strip().splitlines()

    # Try to find where func_code block matches inside the contract
    for i in range(len(contract_lines) - len(func_lines) + 1):
        match = True
        for j in range(len(func_lines)):
            if contract_lines[i + j].strip() != func_lines[j].strip():
                match = False
                break
        if match:
            # Found the func_code block inside contract_lines starting at line i
            # Now we need to find just the first function block inside func_code
            first_func_start = None
            brace_depth = 0
            for k, line in enumerate(func_lines):
                if first_func_start is None and re.match(r'\s*function\s', line):
                    first_func_start = k
                if first_func_start is not None:
                    brace_depth += line.count('{')
                    brace_depth -= line.count('}')
                    if brace_depth == 0:
                        first_func_end = k
                        return i + first_func_start + 1, i + first_func_end + 1  # 1-based lines

    return None, None

async def generate_audit(source: str):
    # Search for matches
    temperature = 0.1
    matched_records = find_record(source, 'db/db1.json')
    if source[:8] == "contract":
        prompt = get_prompt3(source)
        message = reference(prompt)
        json_string = extract_json_string(message)
    elif matched_records:
        # Print results
        for match in matched_records:
            print(f"Matched Hash: {match['hash']}, Type: {match['type']}")
            print('-' * 50)
            start_line, end_line = find_function_position(source, matched_records[0]["code"])
        json_string = f"""
            [
            {{
                "fromLine": {start_line},
                "toLine": {end_line},
                "vulnerabilityClass": "{matched_records[0]["type"]}",
                "description": "audit processing."
            }}
            ]
        """

        
        # prompt = get_prompt2(source, matched_records[0])
        # message = reference(prompt)
        # json_string = extract_json_string(message)
        # prompt = get_gpt_prompt2(matched_records[0])
        # json_string = await gpt_reference(prompt, source)
    else:
        prompt = get_prompt4(source)
        message = reference(prompt)
        print(f"========>source len:{len(source)}")
        if "True" in message and len(source) > 3500: # valid code
            json_string = "[]"
        else:
            json_string = await gpt_reference(get_gpt_prompt(), source)
            # json_string = extract_json_string(message)        

    # show_section(prompt)

    # if mode == 0:
    #     # Tokenize and generate
    #     message = reference(prompt)
    #     json_string = extract_json_string(message)
    # elif mode == 1:
    # else:
    #     # show_section(message)
    #     if "True" in message: # valid code
    #         json_string = "[]"
    #     else:
    #         json_string = await gpt_reference(get_gpt_prompt(), source)
    #         # json_string = extract_json_string(message)

    return json_string


REQUIRED_KEYS = {
    "fromLine",
    "toLine",
    "vulnerabilityClass",
    "description",
}
INT_KEYS = ("fromLine", "toLine")


def try_prepare_result(result) -> list[dict] | list:

    if isinstance(result, str):
        try:
            result = json.loads(result)
        except:
            return []

    if isinstance(result, dict):
        if (
            len(result) == 1
            and isinstance(list(result.values())[0], list)
            and all(isinstance(item, dict) for item in list(result.values())[0])
        ):
            result = list(result.values())[0]
        else:
            result = [result]

    prepared = []
    for item in result:
        for key in REQUIRED_KEYS:
            if key not in item:
                print("not all reqiured fields exist")
                return None
        cleared = {k: item[k] for k in REQUIRED_KEYS}
        # if (
        #     "priorArt" in item
        #     and isinstance(item["priorArt"], list)
        #     and all(isinstance(x, str) for x in item["priorArt"])
        # ):
            # cleared["priorArt"] = item["priorArt"]
        # if "fixedLines" in item and isinstance(item["fixedLines"], str):
        #     cleared["fixedLines"] = item["fixedLines"]
        # if "testCase" in item and isinstance(item["testCase"], str):
        #     cleared["testCase"] = item["testCase"]
        for k in INT_KEYS:
            if isinstance(cleared[k], int) or (
                isinstance(item[k], str) and item[k].isdigit()
            ):
                cleared[k] = int(cleared[k])
            else:
                print("There is not all requried key")
                return None
        prepared.append(cleared)
    return prepared

# Cache: stores up to 10 results
cache = OrderedDict()

def get_hash_index(code: str) -> str:
    """Generate a hash index for the contract code."""
    return hashlib.sha256(code.encode("utf-8")).hexdigest()

@app.post("/submit")
async def submit(request: Request):
    contract_code = (await request.body()).decode("utf-8")
    index = get_hash_index(contract_code)

    # Check cache
    if index in cache:
        print("======cache hit=======")
        for _ in range(15):  # Wait up to 15 seconds
            result = cache.get(index)
            if result != "pending":
                return result
            await asyncio.sleep(1)
        raise HTTPException(status_code=503, detail="Audit is still being processed")

    print("======cache miss=======")
        # Set as pending
    cache[index] = "pending"
    if len(cache) > 20:
        cache.popitem(last=False)

    tries = int(os.getenv("MAX_TRIES", "3"))
    is_valid, result = False, None

    while tries > 0:
        result = await generate_audit(contract_code)
        
        result = try_prepare_result(result)

        if result is not None:
            is_valid = True
            with open("req_history", "a") as f:
                f.write("-"*50 + "\n")
                f.write("task code: " + contract_code + "\n")
                f.write("-"*50 + "\n")
                json.dump(result, f, indent=2)
                f.write("-"*50 + "\n")
            break
        tries -= 1

    if not is_valid:
        raise HTTPException(status_code=400, detail="Unable to prepare audit")

    # # Save to cache (ensure only last 10 are stored)
    # if index not in cache:
    #     if len(cache) >= 20:
    #         cache.popitem(last=False)  # Remove oldest
    cache[index] = result

    return result

@app.get("/healthcheck")
async def healthchecker():
    return {"status": "OK"}

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("SERVER_PORT", "40004")))
